general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'zybpaasabap'
      space: 'DEV'
      credentialsId: 'CF_CREDENTIALSID'

